spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:mysql://172.16.49.61:5627/sampledb?useUnicode=true&characterEncoding=utf-8"
    username: bxhr
    password: Passw0rd
    tomcat:
      initial-size: 10
      min-idle: 10
      max-idle: 30
      max-active: 30
      #min-evictable-idle-time-millis: 72000
      #time-between-eviction-runs-millis: 5000
      #test-while-idle: true
      #validation-interval: 30000
      #validation-query-timeout: 5
      #validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: 172.16.49.243
    port: 6379
    password:
    pool:
      min-idle: 1
      max-active: 10
      max-idle: 5
      max-wait: -1
  data:
    mongodb:
      ## SpringBoot官网文档: 如配置spring.data.mongodb.uri，就要把所有配置都写到此配置项中
      ## 原文："You can set spring.data.mongodb.uri property to change the URL and configure 
      ## additional settings such as the replica set"
      ## mongodb官网关于connection-string的说明:
      ## https://docs.mongodb.com/manual/reference/connection-string/
      uri: "mongodb://172.16.49.243/sample"
  freemarker:
    expose-request-attributes: true
    request-context-attribute: request
  http:
    multipart:
      max-file-size: 1Mb
      max-request-size: 10Mb

coamctech:
  fastdfs:
    connect-timeout: 10
    network-timeout: 30
    charset: UTF-8
    http-tracker-port: 8080
    http-anti-steal-token: false
    http-secret-key: FastDFS1234567890
    tracker-server: 172.16.49.243:22122
  zookeeper:
    curator:
      connection-string: 172.16.49.243:2181
      connection-timeout: 5000
      session-timeout: 10000
      retry-policy-type: exponential-backoff
      retry-policy-base-sleep-time: 5000
      retry-policy-max-retries: 3
      retry-policy-max-sleep-time: 1000
